include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # avoid_print: false
    # prefer_single_quotes: true

analyzer:
  errors:
    deprecated_member_use: ignore
    unused_import: ignore
    unused_field: ignore
    unused_local_variable: ignore
