include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    use_key_in_widget_constructors: true
    annotate_overrides: true
    await_only_futures: true
    camel_case_types: true
    library_prefixes: true
    non_constant_identifier_names: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    slash_for_doc_comments: true

analyzer:
  # No more ignores. We want to see and fix every warning.
